name: skmtdart

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:

dev_dependencies:
  ffigen: ^2.1.0
  test: ^1.16.5


ffigen:
  output: '../../lib/skmtdart_ffi.g.dart'
  name: 'SkmtDartffi'
  headers:
    entry-points:
      - 'skmtdart_ffi.h'
    include-directives:
      - 'skmtdart_ffi.h'

